using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kokomija.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddCouponManagementFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "AccountAgeDays",
                table: "Coupons",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AutoGenerationRuleId",
                table: "Coupons",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CampaignId",
                table: "Coupons",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CampaignName",
                table: "Coupons",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CouponType",
                table: "Coupons",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "DaysAfterBirthday",
                table: "Coupons",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DaysBeforeBirthday",
                table: "Coupons",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Coupons",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "VipTierRequired",
                table: "Coupons",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(2415), new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3305) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3843), new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3844) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3924), new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3927) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3934), new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3939) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3943), new DateTime(2026, 1, 2, 18, 6, 55, 482, DateTimeKind.Utc).AddTicks(3945) });

            migrationBuilder.UpdateData(
                table: "BlogTranslations",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 487, DateTimeKind.Utc).AddTicks(4476), new DateTime(2026, 1, 2, 18, 6, 55, 487, DateTimeKind.Utc).AddTicks(4806) });

            migrationBuilder.UpdateData(
                table: "BlogTranslations",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 487, DateTimeKind.Utc).AddTicks(5133), new DateTime(2026, 1, 2, 18, 6, 55, 487, DateTimeKind.Utc).AddTicks(5133) });

            migrationBuilder.UpdateData(
                table: "Blogs",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "PublishedDate", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 483, DateTimeKind.Utc).AddTicks(7189), new DateTime(2026, 1, 2, 18, 6, 55, 483, DateTimeKind.Utc).AddTicks(4824), new DateTime(2026, 1, 2, 18, 6, 55, 483, DateTimeKind.Utc).AddTicks(7721) });

            migrationBuilder.UpdateData(
                table: "CarouselSlideTranslations",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 507, DateTimeKind.Utc).AddTicks(3738));

            migrationBuilder.UpdateData(
                table: "CarouselSlideTranslations",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 507, DateTimeKind.Utc).AddTicks(4258));

            migrationBuilder.UpdateData(
                table: "CarouselSlides",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "StartDate" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 504, DateTimeKind.Utc).AddTicks(1622), new DateTime(2026, 1, 2, 18, 6, 55, 504, DateTimeKind.Utc).AddTicks(1017) });

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5156));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5494));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5498));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5501));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5847));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5853));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5856));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5860));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5863));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5867));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 11,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5870));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 12,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 478, DateTimeKind.Utc).AddTicks(5910));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9401));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9959));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9962));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9974));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9984));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9986));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9989));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 476, DateTimeKind.Utc).AddTicks(9991));

            migrationBuilder.UpdateData(
                table: "Coupons",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "AccountAgeDays", "AutoGenerationRuleId", "CampaignId", "CampaignName", "CouponType", "CreatedAt", "DaysAfterBirthday", "DaysBeforeBirthday", "IsAutoGenerated", "ValidFrom", "ValidUntil", "VipTierRequired" },
                values: new object[] { null, null, null, null, "general", new DateTime(2026, 1, 2, 18, 6, 55, 494, DateTimeKind.Utc).AddTicks(4408), null, null, false, new DateTime(2026, 1, 2, 18, 6, 55, 493, DateTimeKind.Utc).AddTicks(9987), new DateTime(2026, 7, 2, 18, 6, 55, 494, DateTimeKind.Utc).AddTicks(1137), null });

            migrationBuilder.UpdateData(
                table: "ProductGroups",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 495, DateTimeKind.Utc).AddTicks(8647));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8122));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8659));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8667));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8672));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8677));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8701));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8706));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8728));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8758));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8765));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 11,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8771));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 12,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8775));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 13,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8780));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 14,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8790));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 15,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8798));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 16,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8803));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 17,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8810));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 18,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8862));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 19,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8869));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 20,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8874));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 21,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8879));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 22,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8888));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 23,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8894));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 24,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 498, DateTimeKind.Utc).AddTicks(8898));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7001));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7485));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7490));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7493));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7497));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7517));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7521));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7525));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7528));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7533));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 11,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7538));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 12,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7543));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 13,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7546));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 14,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7549));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 15,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 502, DateTimeKind.Utc).AddTicks(7553));

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 497, DateTimeKind.Utc).AddTicks(4493));

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 497, DateTimeKind.Utc).AddTicks(4920));

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 497, DateTimeKind.Utc).AddTicks(4927));

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(5025), new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(5595) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6244), new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6245) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6249), new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6250) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6255), new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6256) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6259), new DateTime(2026, 1, 2, 18, 6, 55, 489, DateTimeKind.Utc).AddTicks(6260) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 491, DateTimeKind.Utc).AddTicks(9598), new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(23) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(503), new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(503) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(508), new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(509) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(512), new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(513) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(517), new DateTime(2026, 1, 2, 18, 6, 55, 492, DateTimeKind.Utc).AddTicks(517) });

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 1,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5642));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 2,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5962));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 3,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5964));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 4,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5966));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 5,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5969));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 6,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5971));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 7,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5973));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 8,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5975));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 9,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5977));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 10,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5979));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 11,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 488, DateTimeKind.Utc).AddTicks(5982));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 472, DateTimeKind.Utc).AddTicks(5284));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 472, DateTimeKind.Utc).AddTicks(5888));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 472, DateTimeKind.Utc).AddTicks(5892));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 472, DateTimeKind.Utc).AddTicks(5896));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 472, DateTimeKind.Utc).AddTicks(5900));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 472, DateTimeKind.Utc).AddTicks(5903));

            migrationBuilder.UpdateData(
                table: "SupportedLanguages",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 479, DateTimeKind.Utc).AddTicks(7965));

            migrationBuilder.UpdateData(
                table: "SupportedLanguages",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 18, 6, 55, 479, DateTimeKind.Utc).AddTicks(8546));

            migrationBuilder.UpdateData(
                table: "TaxRates",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 493, DateTimeKind.Utc).AddTicks(1), new DateTime(2026, 1, 2, 18, 6, 55, 493, DateTimeKind.Utc).AddTicks(339) });

            migrationBuilder.UpdateData(
                table: "TaxRates",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 493, DateTimeKind.Utc).AddTicks(655), new DateTime(2026, 1, 2, 18, 6, 55, 493, DateTimeKind.Utc).AddTicks(656) });

            migrationBuilder.UpdateData(
                table: "TaxRates",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 18, 6, 55, 493, DateTimeKind.Utc).AddTicks(659), new DateTime(2026, 1, 2, 18, 6, 55, 493, DateTimeKind.Utc).AddTicks(660) });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AccountAgeDays",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "AutoGenerationRuleId",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "CampaignId",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "CampaignName",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "CouponType",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "DaysAfterBirthday",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "DaysBeforeBirthday",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Coupons");

            migrationBuilder.DropColumn(
                name: "VipTierRequired",
                table: "Coupons");

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7349), new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7651) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7947), new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7948) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7951), new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7951) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7954), new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7954) });

            migrationBuilder.UpdateData(
                table: "BlogCategories",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7957), new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(7957) });

            migrationBuilder.UpdateData(
                table: "BlogTranslations",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(214), new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(519) });

            migrationBuilder.UpdateData(
                table: "BlogTranslations",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(845), new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(846) });

            migrationBuilder.UpdateData(
                table: "Blogs",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "PublishedDate", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 824, DateTimeKind.Utc).AddTicks(3266), new DateTime(2026, 1, 2, 17, 35, 18, 824, DateTimeKind.Utc).AddTicks(1962), new DateTime(2026, 1, 2, 17, 35, 18, 824, DateTimeKind.Utc).AddTicks(3559) });

            migrationBuilder.UpdateData(
                table: "CarouselSlideTranslations",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 833, DateTimeKind.Utc).AddTicks(7833));

            migrationBuilder.UpdateData(
                table: "CarouselSlideTranslations",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 833, DateTimeKind.Utc).AddTicks(8140));

            migrationBuilder.UpdateData(
                table: "CarouselSlides",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "StartDate" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 833, DateTimeKind.Utc).AddTicks(1491), new DateTime(2026, 1, 2, 17, 35, 18, 833, DateTimeKind.Utc).AddTicks(1160) });

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(3914));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4225));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4228));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4231));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4550));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4556));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4559));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4562));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4564));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4567));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 11,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4570));

            migrationBuilder.UpdateData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 12,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 822, DateTimeKind.Utc).AddTicks(4573));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1147));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1494));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1497));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1499));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1501));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1504));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1506));

            migrationBuilder.UpdateData(
                table: "Colors",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 821, DateTimeKind.Utc).AddTicks(1508));

            migrationBuilder.UpdateData(
                table: "Coupons",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "ValidFrom", "ValidUntil" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 829, DateTimeKind.Utc).AddTicks(3071), new DateTime(2026, 1, 2, 17, 35, 18, 829, DateTimeKind.Utc).AddTicks(1438), new DateTime(2026, 7, 2, 17, 35, 18, 829, DateTimeKind.Utc).AddTicks(1752) });

            migrationBuilder.UpdateData(
                table: "ProductGroups",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 829, DateTimeKind.Utc).AddTicks(7942));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4339));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4676));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4679));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4712));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4715));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4722));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4724));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4727));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4731));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4735));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 11,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4737));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 12,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4739));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 13,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4741));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 14,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4744));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 15,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4746));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 16,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4748));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 17,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4753));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 18,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4757));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 19,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4760));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 20,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4762));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 21,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4765));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 22,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4767));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 23,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4770));

            migrationBuilder.UpdateData(
                table: "ProductImages",
                keyColumn: "Id",
                keyValue: 24,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 831, DateTimeKind.Utc).AddTicks(4772));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4133));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4466));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4468));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4470));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4472));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4495));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4498));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4499));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4501));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4504));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 11,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4509));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 12,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4511));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 13,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4513));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 14,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4515));

            migrationBuilder.UpdateData(
                table: "ProductVariants",
                keyColumn: "Id",
                keyValue: 15,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 832, DateTimeKind.Utc).AddTicks(4517));

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 830, DateTimeKind.Utc).AddTicks(7267));

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 830, DateTimeKind.Utc).AddTicks(7568));

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 830, DateTimeKind.Utc).AddTicks(7571));

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(5629), new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(5939) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6238), new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6239) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6242), new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6242) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6245), new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6245) });

            migrationBuilder.UpdateData(
                table: "ShippingProviders",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6248), new DateTime(2026, 1, 2, 17, 35, 18, 826, DateTimeKind.Utc).AddTicks(6248) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6159), new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6462) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6761), new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6761) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6764), new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6764) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6767), new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6768) });

            migrationBuilder.UpdateData(
                table: "ShippingRates",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6771), new DateTime(2026, 1, 2, 17, 35, 18, 827, DateTimeKind.Utc).AddTicks(6772) });

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 1,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8282));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 2,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8589));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 3,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8591));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 4,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8593));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 5,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8595));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 6,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8596));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 7,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8629));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 8,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8631));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 9,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8633));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 10,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8635));

            migrationBuilder.UpdateData(
                table: "SiteSettings",
                keyColumn: "Id",
                keyValue: 11,
                column: "UpdatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 825, DateTimeKind.Utc).AddTicks(8637));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 819, DateTimeKind.Utc).AddTicks(4642));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 819, DateTimeKind.Utc).AddTicks(4964));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 819, DateTimeKind.Utc).AddTicks(4966));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 819, DateTimeKind.Utc).AddTicks(4969));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 819, DateTimeKind.Utc).AddTicks(4971));

            migrationBuilder.UpdateData(
                table: "Sizes",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 819, DateTimeKind.Utc).AddTicks(4973));

            migrationBuilder.UpdateData(
                table: "SupportedLanguages",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(381));

            migrationBuilder.UpdateData(
                table: "SupportedLanguages",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 1, 2, 17, 35, 18, 823, DateTimeKind.Utc).AddTicks(690));

            migrationBuilder.UpdateData(
                table: "TaxRates",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 828, DateTimeKind.Utc).AddTicks(2982), new DateTime(2026, 1, 2, 17, 35, 18, 828, DateTimeKind.Utc).AddTicks(3276) });

            migrationBuilder.UpdateData(
                table: "TaxRates",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 828, DateTimeKind.Utc).AddTicks(3570), new DateTime(2026, 1, 2, 17, 35, 18, 828, DateTimeKind.Utc).AddTicks(3570) });

            migrationBuilder.UpdateData(
                table: "TaxRates",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2026, 1, 2, 17, 35, 18, 828, DateTimeKind.Utc).AddTicks(3573), new DateTime(2026, 1, 2, 17, 35, 18, 828, DateTimeKind.Utc).AddTicks(3573) });
        }
    }
}
