using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Kokomija.Entity
{
    public class Coupon
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Code { get; set; } = string.Empty;

        [MaxLength(200)]
        public string? Description { get; set; }

        [Required]
        [MaxLength(50)]
        public string DiscountType { get; set; } = "percentage"; // percentage, fixed_amount

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal DiscountValue { get; set; }

        /// <summary>
        /// Type of coupon: general, birthday, new_user, vip, category, product, first_purchase
        /// </summary>
        [Required]
        [MaxLength(50)]
        public string CouponType { get; set; } = "general";

        [Column(TypeName = "decimal(18,2)")]
        public decimal? MinimumOrderAmount { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? MaximumDiscountAmount { get; set; }

        public int? UsageLimit { get; set; }

        public int UsageCount { get; set; } = 0;

        public int? UsageLimitPerUser { get; set; }

        public DateTime? ValidFrom { get; set; }

        public DateTime? ValidUntil { get; set; }

        public bool IsActive { get; set; } = true;

        [MaxLength(100)]
        public string? StripeCouponId { get; set; }

        [MaxLength(100)]
        public string? StripePromotionCodeId { get; set; }

        // User-specific coupon (if null, available to all users)
        public string? UserId { get; set; }
        [ForeignKey("UserId")]
        public ApplicationUser? User { get; set; }

        // Product restriction (if set, coupon only valid for this specific product)
        public int? ProductId { get; set; }
        [ForeignKey("ProductId")]
        public Product? Product { get; set; }

        // Category restriction (if set, coupon only valid for products in this category)
        public int? CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category? Category { get; set; }

        // VIP Tier requirement (if set, only users with this tier or higher can use)
        [MaxLength(50)]
        public string? VipTierRequired { get; set; }

        // Birthday coupon settings
        public int? DaysBeforeBirthday { get; set; }
        public int? DaysAfterBirthday { get; set; }

        // New user coupon settings (account age in days)
        public int? AccountAgeDays { get; set; }

        // Auto-generation settings
        public bool IsAutoGenerated { get; set; } = false;
        
        [MaxLength(100)]
        public string? AutoGenerationRuleId { get; set; }

        // Batch/Campaign tracking
        [MaxLength(100)]
        public string? CampaignId { get; set; }

        [MaxLength(200)]
        public string? CampaignName { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? UpdatedAt { get; set; }

        // Navigation properties
        public ICollection<Order> Orders { get; set; } = new List<Order>();
        public ICollection<CouponUsage> CouponUsages { get; set; } = new List<CouponUsage>();

        // Helper properties
        [NotMapped]
        public bool IsExpired => ValidUntil.HasValue && ValidUntil.Value < DateTime.UtcNow;

        [NotMapped]
        public bool IsFullyUsed => UsageLimit.HasValue && UsageCount >= UsageLimit.Value;

        [NotMapped]
        public bool IsValid => IsActive && !IsExpired && !IsFullyUsed && 
                              (!ValidFrom.HasValue || ValidFrom.Value <= DateTime.UtcNow);
    }
}
